---
slug: TPM-v3
filename: TPM-v3
title: The Positioning Manual for Technical Firms
subtitle: v3 (BETA build 1)
description: 
author: Philip Morgan
copyright: 2019
uuid: 77ca2d19-d17b-4dfb-9e3e-e7729e59fe4d
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
